name = 'BY:RP Development'
port = 7788
players = 128
# password = 'ultra-password'
announce = false
# token = 'YOUR_TOKEN'
gamemode = 'Freeroam'
website = 'example.com'
language = 'en'
description = 'alt:V Sample Server'
modules = ['csharp-module']
resources = ['server', 'client']
debug = true
spawnAfterConnect = false
enableSyncedMetaData = false

[csharp-module]
disableDependencyDownload = true
